### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by quchen** [curry-club-aux/haskell-workshop#2]
- `(.).(.)` sieht nicht aus wie ein Smiley. `(:[])` ist der Robot Monkey Operator, so sieht ein Gesicht aus.
- "null" klingt komisch als Rückgabewert von `maximum'`, "0" wäre deutlicher.
- Fibonacci: jede Zahl ist die Summe ihrer _beiden_ Vorgänger

**Comment by iblech** [comment]
- Ha, diese Bezeichnung für `(:[])` kannte ich noch nicht! Kennt jemand einen anderen lustigen Namen für `(.).(.)`?
- Danke, korrigiert.
- Danke, korrigiert.

**Comment by noschinl** [comment]
Ich kenne `(.).(.)` als Owl- bzw. Boobs-Operator.

**Comment by iblech** [comment]
Dann korrigiere ich das gleich zu "Eulen-Operator". Danke!

**Comment by timjb** [comment]
Eulenoperator wird @ThinkCaren gefallen :-)

**Comment by ThinkCaren** [comment]
Da hat @timjb ja sowas von recht!! Eulen, Eulen, Eulen!!!
