### ISSUE TITLE
zu Blatt 2/Aufgabe 2

### ISSUE THREAD

**Issue by GraffL** [curry-club-aux/haskell-workshop#4]
Die Funktion in b) multipliziert momentan das erste und das letzte (nicht _vor_letzte) Element der Liste (Last von Tail ist das gleiche wie Last von der ursprünglichen Liste).
Evtl. safeLast durch safeHead ersetzen (dann werden ersten und zweites Element der Liste multipliziert)?

**Comment by iblech** [comment]
Danke! Ist korrigiert. :-) Weitere Pull Requests sind willkommen!
