### ISSUE TITLE
Lizenz!

### ISSUE THREAD

**Issue by Profpatsch** [curry-club-aux/haskell-workshop#5]
Welche Lizenz wollt ihr dem Repo denn geben?

**Comment by timjb** [comment]
Ich bin für CC BY

**Comment by richi235** [comment]
Ich bin für die CC-BY-NC-SA oder die GFDL die GNU Free Documentation License. Letztere verwenden auch viele Professoren für ihre Scripte und sie ist auch gut für bachelorarbeiten und Masterarbeiten geeignet. Sie ist der CC-BY-NC-SA sehr ähnlich, enthält aber, dass jemand wenn er/sie das werk kopiert und erweitert dass auf jeden fall mit/in einem versionskontrollsystem tun muss. Und das finde ich toll :)

**Comment by Profpatsch** [comment]
Ich finde CC in diesem Fall besser ohne NC, da man das Tutorial sonst nicht als Vorlage oder Inspiration für bezahlte Kurse nutzen könnte (oder es zumindest nicht rechtlich eindeutig ist, ob man das kann).

**Comment by richi235** [comment]
wegen NC: stimmt, gutes argument, bin überzeugt. 

Ich glaube die GFDL hat sowieso kein NC dabei und ist diesbezüglich sowieso unproblematisch.

**Comment by Profpatsch** [comment]
Ich glaube wir sollten noch die Meinungen von @iblech und @sternenseemann einholen, weil sie die anderen Mitautoren sind.

**Comment by sternenseemann** [comment]
CC BY SA wäre mein favorit denke ich, NC finde ich immer schwierig (man hat ja auch eh schon SA), aber mir egal, finde nur GFDL unnötig hier.

**Comment by timjb** [comment]
Bisheriger Favorit hier ist die CC BY SA. Ich wäre damit auch einverstanden. @iblech Du auch?

**Comment by richi235** [comment]
@sternenseemann : warum findest du die GFDL hier unnötig?

**Comment by iblech** [comment]
On Fri, Aug 03, 2018 at 01:49:21PM +0000, Tim Baumann wrote:
> Bisheriger Favorit hier ist die CC BY SA. Ich wäre damit auch einverstanden. @iblech Du auch?

Ja! CC BY SA ist meine Lieblingslizenz.

Die NC-Klausel ist prinzipiell gut gemeint, in Wahrheit aber problematisch:
https://irights.info/wp-content/uploads/userfiles/CC-NC_Leitfaden_web.pdf

**Comment by Profpatsch** [comment]
Okay, implementiert in https://github.com/curry-club-aux/haskell-workshop/commit/4e3e434765a88e631388102d19db41b1ddeb285f
